### ISSUE TITLE
Towny border moved?

### ISSUE THREAD

**Issue by metype** [SilentRoses/Farnetworks#11]
On the towny server me and lucky had a nice island area and had an outpost there, since then the border has apparently shrunk and everything there is inaccessible as it is now outside the border and is instant death. This is kind of an issue as we at least want to materials from the build back.

**Comment by SilentRoses** [comment]
I'll extend the border to 40,000 tomorrow!

**Comment by SilentRoses** [comment]
Border size has been doubled from 30,000 to 60,000. Hope this fixed your issue!
