### ISSUE TITLE
Voting broken; Bungeecord Query Disabled?

### ISSUE THREAD

**Issue by ReEvadere** [SilentRoses/Farnetworks#12]
I’ve noticed that you are using Rewardvoting plugin throughout the bungee network through the proxy. I also saw that the website is displaying 0 users online the server, which may be a Query problem. My speculation is that on the bungee cord proxy server in the config.yml the query field is disabled. 

If there is a port forwarding error being thrown, enabling the query might fix it.

**Comment by SilentRoses** [comment]
Thanks, i'll attempt this now!

**Comment by SilentRoses** [comment]
Heya, turns out its already enabled! Thanks for the idea though. I'll look into the voting issue!

**Comment by SilentRoses** [comment]
Voting should work now.
