### ISSUE TITLE
Newest version of pixelmon is buggy.

### ISSUE THREAD

**Issue by aNem0** [SilentRoses/Farnetworks#18]
When battling there is a chance the animation will stop and you will be stuck in battle causing you to have to stop minecraft then after that you are not able to catch pokemon. and you cannot accept tpa request the message that comes is you do not have any pending request.

**Comment by SilentRoses** [comment]
There is a command to end battles, it's /endbattle. It's an issue on pixelmons end and i cannot fix it.
