### ISSUE TITLE
problem at hub

### ISSUE THREAD

**Issue by SouldrionOP456** [SilentRoses/Farnetworks#2]
Yes, 1st you can take damage which I don't think is healthy for players in the hub but okay. 2nd the most important, you lose hunger bar in the lobby which could lead to not being able to run. Thank you for reading + The torch with invisibility is not working for me because "you are not permitted to use TORCH" it says while it does not work.

**Comment by SilentRoses** [comment]
On my to do list thanks :P

**Comment by SouldrionOP456** [comment]
yep like to help ^^

**Comment by metype** [comment]
I reported this like a month ago now lol

**Comment by SilentRoses** [comment]
Both issues resolved, thank you for reporting this. If you remind me ingame ill give u a few free crate keys!
