### ISSUE TITLE
Towny Membership Name Bug

### ISSUE THREAD

**Issue by metype** [SilentRoses/Farnetworks#22]
I recently, for October changed my IGN to "SpookType" I then, simply wanted to play some towny and after a little fun in the Nether I went to go back to my town so I typed "/town spawn" and it said "You are not part of a town", confused I checked "Everest" my town, and surly enough the Owner was "Metype", not "SpookType", I am now locked out of my town until November 5th when I can change my name back, I would appreciate help.

**Comment by SilentRoses** [comment]
There may be a fix for this in a later version. I'll keep my eyes open and i'll report it to the plugin developer.

**Comment by SilentRoses** [comment]
Fixed

**Comment by SilentRoses** [comment]
Fixed
