### ISSUE TITLE
Hardcore smp gamemode bug.

### ISSUE THREAD

**Issue by aNem0** [SilentRoses/Farnetworks#23]
Whenever you die in HardcoreSmp you are set into spectator however if you were to go to /hub and then back to HardcoreSmp you will be set to survival. And will be allowed to play again.

**Comment by SilentRoses** [comment]
Looking into it.

**Comment by SilentRoses** [comment]
Okay so this actually isnt a bug. It's because the server is in hardcore mode. EG when you die you can't respawn. Nothing i can do about it. Sorry!
