### ISSUE TITLE
Ore Gens // OP Skyblock

### ISSUE THREAD

**Issue by Oemidin** [SilentRoses/Farnetworks#24]
Ya girls tryina do some mining, get some cash money diamonds, but here I am running the generator over and over again getting only cobblestone. Pls. Even smooth stone would make me happy TwT
- When others are online, mainly staff, the ore gen works perfectly fine
- When am all aloney I just get cobbley blox
- The generator isn't the problem as it works just fine when others are online
- We don't get coal in the gens; smelting iron/gold is suddenly harder than expected
Pls fix thank u ily

**Comment by SilentRoses** [comment]
Should be fixed now <3
