### ISSUE TITLE
OP Skyblock // Literally Everything (Almost)

### ISSUE THREAD

**Issue by Oemidin** [SilentRoses/Farnetworks#25]
- Powered pistons don't push any blocks in our cobble gen that they typically would push and did push before last ore gen fix
- Land claims/island settings seem skewed, way of describing is unknown but I get land claim prompts I didn't before ("other players can build here too"), can't kill island mobs but can place and break blocks on the island
- /is mission is suddenly VERY bossy, every time I obtain cobble it prompts me to run the command to complete the mission - didn't experience this before the last ore gen fix

Gud luck boss ily

**Comment by Oemidin** [comment]
Further issues/complaints:
- Plz can we have a shop that has item frames to show what we're buying, and saplings available in shops
- Any person on our island can place a chest in the center of their platform and immediately claim all centers of all platforms because of the land claims/claim shovel plugin existing on OPSB
- Can't access island setting menus
- An Iris ranked player couldn't use /is warp Oemidin or /is warp Cabblestone

Comments from community:
- Easier to reset OPSB and use the old plugin, which would allow us to have our own island connected by bridges since we were mostly close together
- If it gets harder and harder to fix the server it'd be best to reset to something we relied on for longer
- All players should have equal chances of ore spawns from their generator, even though the appeal of 'higher rank = more/better ores' seems great in theory, when your generator only produces cobble it's a bit depressing

Love u feebe do what u gotta do

**Comment by Cabblestone** [comment]
Another comment is, that commands are either glitched or hard to use. I feel like switching back to the old plugin would be very helpful for players. The old plugin had everything compacted into one menu and clearly defined what it was kinda like the compass menu in hubs.

**Comment by SilentRoses** [comment]
Okay so i actually updated the skyblock issues to try and fix a bunch of issues, should i try and downdate the version or do a reset o.o

**Comment by Cabblestone** [comment]
I suggest downdating it for now and if there is continued problems a reset.

**Comment by SilentRoses** [comment]
Should be fixed now UwU
