### ISSUE TITLE
Name membership issue in towny still exists

### ISSUE THREAD

**Issue by metype** [SilentRoses/Farnetworks#29]
![thisisannoying](https://user-images.githubusercontent.com/39036543/68096606-6c1e5000-fe77-11e9-8d92-b0bb94c3b6c6.PNG)
The issue I reported before was marked as fixed.
It is not fixed.
I still am having issues actually being a member of the town I own.

**Comment by SilentRoses** [comment]
That's because you had this issue before the update.
