### ISSUE TITLE
Hub welcome message

### ISSUE THREAD

**Issue by Cabblestone** [SilentRoses/Farnetworks#30]
I wish I could get a picture but it goes away to fast. It says “IGN, Welcome to far opsb”

**Comment by SilentRoses** [comment]
More info required pls

**Comment by Cabblestone** [comment]
![ED831781-98D4-4AAE-9579-A6ED46358562](https://user-images.githubusercontent.com/52842798/68237480-31322e80-ffd5-11e9-99b1-29602b846be2.jpeg)
Literally all I could get you.

**Comment by SilentRoses** [comment]
Fixed
