### ISSUE TITLE
Sugar Cane & Bamboo Growth

### ISSUE THREAD

**Issue by LozMoz** [SilentRoses/Farnetworks#36]
on server seems limited to only going to first stage or so (sugar cane doesnt grow and bamboo just sprouts), u can use bone meal however to force bamboo to grow so doesnt seem like a mc side issue,

**Comment by SilentRoses** [comment]
Should be sorted in 1.15.1 update. if not please leme know. ticket will remain open until confirmed as fixed

**Comment by SilentRoses** [comment]
Issue resolved.
