### ISSUE TITLE
You are not allowed to use, etc.

### ISSUE THREAD

**Issue by metype** [SilentRoses/Farnetworks#4]
I don't think every time you right click on a block or right click with an item in the hub, the chat should tell you in dark red you're not allowed to do that, chests? Maybe, but every block, with every item? It feels... Unsettling when I'm choosing a server and right click the compass and get scolded by the chat

**Comment by SilentRoses** [comment]
Will work on this, for now can you supply screenshots please.

**Comment by metype** [comment]
![2019-07-14_16 44 13](https://user-images.githubusercontent.com/39036543/61189708-d73ce000-a656-11e9-837a-d102e784aa80.png)
Screenshot

**Comment by SilentRoses** [comment]
This should be resolved now, If its not please reopen this!
