### ISSUE TITLE
BeeSMP Kits

### ISSUE THREAD

**Issue by metype** [SilentRoses/Farnetworks#41]
Yes, I know that with new version and stuff plugins can break, but it appears that every single kit in BeeSMP is broken in some way, monthly only gives you the stack of steak, etc. Using any of the kits gives you the error "That kit is improperly defined. Contact an administrator."

**Comment by SilentRoses** [comment]
im fully aware thanks for adding here though. every update seems to break them. ill fix them when im free.

**Comment by SilentRoses** [comment]
Fixed, thank you for the bug report!
