### ISSUE TITLE
Crate Bugs

### ISSUE THREAD

**Issue by ReEvadere** [SilentRoses/Farnetworks#43]
https://cdn.discordapp.com/attachments/547950223503261718/663737777615273985/unknown.png

Winning 2 Rare crate keys gives 3.

**Comment by LozMoz** [comment]
Second Crate issue: God Crate
https://cdn.discordapp.com/attachments/547950223503261718/668628596104888321/unknown.png
but no god crate in the /cc command
![image](https://user-images.githubusercontent.com/59422388/72692963-cb960e80-3afc-11ea-99f6-08c5a81cdf42.png)

**Comment by SilentRoses** [comment]
God crate isn't supposed to be in the menu, also warp crates has been fixed.

Crate issue regarding keys being worked on now.

**Comment by SilentRoses** [comment]
Fixed
