### ISSUE TITLE
Far Towny Vulcan Kit (from crate)

### ISSUE THREAD

**Issue by LozMoz** [SilentRoses/Farnetworks#44]
![image](https://user-images.githubusercontent.com/59422388/72767416-c8188b00-3bc1-11ea-8a15-3bc7ee3564ba.png)

by looks its probably something to do with the id.

**Comment by SilentRoses** [comment]
Server: towny

**Comment by SilentRoses** [comment]
Should be fixed now. Crates have been updated on all servers. If not it's to do with the magic plugin being out of date which is now updated.
