### ISSUE TITLE
Linking in hub

### ISSUE THREAD

**Issue by LozMoz** [SilentRoses/Farnetworks#46]
well said to use /discord unlink to unlink since had me link but wasnt showing online causing all sorts of LP issues, ran the command along with the /discordsrv unlink neither one removed the link. showed account linked but had no perms to use any commands like /heal /fly /gmc /gmsp so on in any of the servers besides hub till went to another server then affected hub as well.

**Comment by SilentRoses** [comment]
issue resolved. new system in place.
