### ISSUE TITLE
Common Crate + Spawner Crate

### ISSUE THREAD

**Issue by LozMoz** [SilentRoses/Farnetworks#48]
the one shows 25k cash but only receive 10k 

![image](https://user-images.githubusercontent.com/59422388/74590306-30993300-4fdb-11ea-8c66-66758902a316.png)

**Comment by LozMoz** [comment]
Spawner Crate when win the pig spawner doesnt give any sort of spawner.

**Comment by SilentRoses** [comment]
cries

**Comment by SilentRoses** [comment]
Fixed
