### ISSUE TITLE
1.13+ Skyblock

### ISSUE THREAD

**Issue by Cabbs12** [SilentRoses/Farnetworks#49]
I was wanting to suggest moving OPSB to a new version, to keep it going with all of the updates and all. I suggest we update it to the most recent Minecraft version for thats available. I say this because of you play past 1.12.2 right now you won’t get any of the nice things that the new versions offer (turtles, new blocks, bees, honey, fire pits, lanterns, drowned, new fish, etc.) I feel like updating to the newest version can add a lot more to OPSB!

**Comment by SilentRoses** [comment]
updating to 1.15.1

**Comment by Cabbs12** [comment]
Make sure you update the plugin version as well :)
Oh I also have an issue, I tried to login this morning on 1.15.1 and got this error: Exception Connecting:QuietException : Unexpected packet received during server login process!
1b8f017b227472616e736c617465223a

**Comment by SilentRoses** [comment]
Releasing soon. Issue resolved.
