### ISSUE TITLE
Problem on discord

### ISSUE THREAD

**Issue by aNem0** [SilentRoses/Farnetworks#5]
Donator chat no longer will say when a purchase is made. Our peeps need recognition for there donations

**Comment by SilentRoses** [comment]
Nemo more info please, it is all packages or certain packages as its limited to only notify when prefixes & suffixes were purchased and when ranks were purchased.

please followup :P

**Comment by aNem0** [comment]
Metype's purchases of the Rift and quest were not posted. The last purchase was 05/26/2019 as of the bot

**Comment by SilentRoses** [comment]
Okay i'll up the priority and get to work tomorrow :P thanks

**Comment by SilentRoses** [comment]
unfixable. Closed!
