### ISSUE TITLE
Job Plugin for BeeSmp and FarEarth

### ISSUE THREAD

**Issue by Cabbs12** [SilentRoses/Farnetworks#51]
Can’t really link it rn but I can’t get it later, bee is just a race for the most money and earth amp would benefit from it.

**Comment by Cabbs12** [comment]
https://www.spigotmc.org/resources/jobs-reborn.4216/?__cf_chl_jschl_tk__=6154bc6886e9aeab5387a011c084edd81eb530c3-1583085101-0-AbtICx2ShwRpBSects1VyOl95XaJ3E1KnvQpQkqeBSiocVxMyZVk_NbGJ76Md41Pc430K2otTiGU0oHsNm8-Kzud2LSckhgcLIcy-yTbGHBEMl_W4ObMnQD46jo2mIUNKnnBe-lp0H70QNvTSODo51Z1G8X_DZpPOsAzwoUAJ8SYkrJqHovQtBL_aoQ-Nx0mkMGAOCSS_5OHuVeG3-hseY6luhcA5v9m92eOv_qciLC69-bhvUmD36FLeOu8MG1NkeJ4JKW8ukxlhkGsKT_ctae0I7BxzsCmdzml8i7hIKAyb5sKvW3me8Km0n3VZOrdEg Here’s the link

**Comment by SilentRoses** [comment]
Earth temporarily closed so closing ticket.
