### ISSUE TITLE
Check on shop and sell hand.

### ISSUE THREAD

**Issue by aNem0** [SilentRoses/Farnetworks#53]

**Comment by SilentRoses** [comment]
Nemo please add more info into these issues as it's quite hard to go from with little info.

**Comment by SilentRoses** [comment]
EG servers?

**Comment by aNem0** [comment]
Cabbs requested I send this in she did not give me anymore info than this.

**Comment by aNem0** [comment]
Ive gotten no more complaints about this. Maybe a false bug?

**Comment by Cabbs12** [comment]
There was literally no other info. We had people selling items and not getting the correct money amount worth them.

**Comment by Cabblestone** [comment]
![2020-04-10_17 26 54](https://user-images.githubusercontent.com/52842798/79031113-83ade300-7b51-11ea-83b8-9c09f44170f5.png)
Hi! I found that maybe either the plugin might glitch and not give correct amount of items bought, seen it on Bee, Earth, and Towny so far!

**Comment by SilentRoses** [comment]
pretty sure this was fixed with CMI
