### ISSUE TITLE
Diamonite kit boots do not have mending

### ISSUE THREAD

**Issue by aNem0** [SilentRoses/Farnetworks#55]

**Comment by SilentRoses** [comment]
More info required. EG servers.

**Comment by aNem0** [comment]
This was reported by a player I do not have the kit to show a picture atm although from what ive seen most of the servers diamonite boots do not have mending while the rest of the set does.

**Comment by aNem0** [comment]
Fartowny-
https://gyazo.com/91476cad3c11ec1b5b4ed468fcffc5cb
https://gyazo.com/3b3f515d6adb0729684a7778fcf8c95c
https://gyazo.com/fc759e8f9ac97114f735e7d72998bf78
https://gyazo.com/c5f62397d7a5463b91a4de8d4c8f941d
Pixelmon's kit are fine and Bee was in another issue.

**Comment by SilentRoses** [comment]
Could we check if this is fixed since update @aNem0 @LozMoz Thanks

**Comment by LozMoz** [comment]
Boots have mending (checked on beesmp and fartowny)
