### ISSUE TITLE
Suggestion- Remove Spawner Crates from Pixelmon crate menu

### ISSUE THREAD

**Issue by aNem0** [SilentRoses/Farnetworks#58]

**Comment by LozMoz** [comment]
or possibly change to shrines / rare pokeballs

**Comment by Fiend-V** [comment]
Spawner crates / keys have been removed.
There are already rare pokeballs in the crates system so adding more would destabilize the crates system.
Issue closed for now.
We'll brainstorm the possibility of shrines in the future.
