### ISSUE TITLE
Bee Smp boots do not have mending

### ISSUE THREAD

**Issue by aNem0** [SilentRoses/Farnetworks#63]

**Comment by SilentRoses** [comment]
More info needed, please post more info and possibly an image.

**Comment by aNem0** [comment]
https://gyazo.com/df42b45a84b73acb024df1f3d29cb065
https://gyazo.com/6c88dfeb82ebf98a516ec5d3833ff257
https://gyazo.com/3b3ade11b79360a34dc5fd928c334722
https://gyazo.com/a0e91a960d8a9f0538b3d4e8c485d063
The boots dont have mending while the rest do not.

**Comment by LozMoz** [comment]
Diamonite boots has mending.
