### ISSUE TITLE
BeeSMP crate issues

### ISSUE THREAD

**Issue by aNem0** [SilentRoses/Farnetworks#64]
https://gyazo.com/2dd9602db466b8faf5a9e9692deecd5d
Common create $25,000 gives $10,000 Rare key from 
common crate does not give actual percent for rare key spawn just the symbol %

**Comment by SilentRoses** [comment]
On my to-do list, could you possibly check if this issue occurs on any other crates. Thanks.

**Comment by aNem0** [comment]
Common Crate also does not give a number following the percent of legendary key reward. As Does the Uncommon Crate, and Rare Crate.

**Comment by SilentRoses** [comment]
Updated along with all other crates.
