### ISSUE TITLE
BeeSMP unsafe /wild

### ISSUE THREAD

**Issue by aNem0** [SilentRoses/Farnetworks#68]
https://gyazo.com/02dd192af5d560f3ad1ee92e9f24c3bc

**Comment by ReEvadere** [comment]
./Wild and ./RTP are disabled in the Nether and end as well. Not sure if intended.

**Comment by SilentRoses** [comment]
This is intended because there is too much lava for the plugin to find safe spots within the given block radius.  I also kinda don't want a nether file size as big as the default towny size xD We're already at over 10GB and i launched it a few days ago.
