### ISSUE TITLE
Bamboo and Sugarcane

### ISSUE THREAD

**Issue by RealxAlucard** [SilentRoses/Farnetworks#70]
Howdy, while playing BeeSMP, I've come to notice how bamboo and sugarcane crops do not grow at their normal tick rate as compared a singleplayer world, which is much faster. They're slow and methodical, still reaching their growth eventually.

Best,
xAlucard

**Comment by SilentRoses** [comment]
I'll take a look, the tick speed shouldn't of been changed. If it's slow i'll double the speed and see if that resolves your issue :)

**Comment by SilentRoses** [comment]
Fixed in recent updates.
