### ISSUE TITLE
Spawner Crate Bug

### ISSUE THREAD

**Issue by aNem0** [SilentRoses/Farnetworks#77]
When a player wins a pig spawner from the crate it tells them they want it but does not give a spawner.

**Comment by aNem0** [comment]
Another spawner that seems bugged is the Elder Gaurdian. Since I did not receive it upon winning it in the crate.

**Comment by LozMoz** [comment]
(the pig spawner is basically every server so far happens on beesmp, fartowny, and opsbee)

**Comment by Fiend-V** [comment]
Pig spawner should now be fixed due to typo. 
I can't find anything wrong with elderguardianspawner. Will continue to run some tests.

**Comment by Fiend-V** [comment]
Pig spawners should now be given successfully across all servers. Tested each spawner and ran spawner crate keys and have found no other issues.
Closing for now. 
If any further issues pop up please make a dedicated ticket for that new issue.
