### ISSUE TITLE
Request adding 1 suffix and 1 staff prefix to menus

### ISSUE THREAD

**Issue by Fiend-V** [SilentRoses/Farnetworks#79]
1.) Add &8[&6&lOfficial Beta Tester&8] to SUFFIX as a limited edition suffix only obtainable by being given it in service of beta testing new servers.

2.) Add &c[&d&lHigh Overlord&c] with same weight as Founder because founder is kinda disturbing me a bit.

Please add to both menus and tab function (instead of F for founder, maybe a HO if possible. Would be hilarious)

Appreciate it in advanced

**Comment by SilentRoses** [comment]
Added, thank ya fiendy <3
