### ISSUE TITLE
OpsBee warps / spawn commands.

### ISSUE THREAD

**Issue by LozMoz** [SilentRoses/Farnetworks#98]
The /warp Crates = Invalid World while /spawn = null.

possible cause is miss spelling of world name in essentials config. (nemo)

![image](https://user-images.githubusercontent.com/59422388/83078898-a5532300-a048-11ea-910e-98d088821a01.png)

**Comment by Fiend-V** [comment]
Spawn and all warps (except club rosie) now operate as normal.
